[patch.'https://github.com/oscomp/arceos.git']
axstd = { path = ".arceos/ulib/axstd" }
arceos_posix_api = { path = ".arceos/api/arceos_posix_api" }
axhal = { path = ".arceos/modules/axhal" }
axmm = { path = ".arceos/modules/axmm" }
axtask = { path = ".arceos/modules/axtask" }
axsync = { path = ".arceos/modules/axsync" }
axruntime = { path = ".arceos/modules/axruntime" }
axns = { path = ".arceos/modules/axns" }
axfs = { path = ".arceos/modules/axfs" }
axconfig = { path = ".arceos/modules/axconfig" }